### ISSUE TITLE
QALD 3 Test without answers

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/NLIWOD#2]
As you can see here (http://gerbil-qa.aksw.org/gerbil/experiment?id=201606010001) SINA gets a score of 1 at QALD 3. That is, the questions have no answers. Please add the correct dataset to qa.datasets.

**Comment by JonathanHuthmann** [comment]
Since: https://github.com/AKSW/NLIWOD/commit/eba284485f8a4d86261ea0f561a50d14e4f12fde
Changed loaders to fix missing answers on QALD3, but still dirty datasets:
![unbenannt](https://cloud.githubusercontent.com/assets/17477322/17251528/79227120-55a9-11e6-909c-262c5ca0b15e.JPG)

(Run main on LoaderController for this post)

**Comment by RicardoUsbeck** [comment]
Pleas fix or at least have a look at QALD2 test and qald 2musicbrainz before closing this ticket.

**Comment by JonathanHuthmann** [comment]
QUALD2__test_dbpedia and QUALD2_test_musicbrainz have no answers in File (only sparql) 
See here:
https://github.com/ag-sc/QALD/blob/master/2/data/dbpedia-test.xml
https://github.com/ag-sc/QALD/blob/master/2/data/musicbrainz-test.xml

**Comment by RicardoUsbeck** [comment]
Ah I see
