### ISSUE TITLE
HawK resources and tools

### ISSUE THREAD

**Issue by Rawank** [AKSW/NLIWOD#25]
Hello,
I'm really interested in getting into HawK
However, when tried to test the system locally, i found some differences between the published paper and the documentation on gitHub

So on Hawk online QA website, are the used tools and techniques the ones on the published paper?

If they are not could you plz tell which DBpedia version, parsing tool, free text resources, pruning techniques and ranking techniques that are used.

Any clarification would be much appreciated

**Comment by RicardoUsbeck** [comment]
Hi Rawank, 

I am sorry for any inconvenience but HAWK is under development and moved far since we published it 1,5 years ago. The numbers from the paper are actually only hard to reproduce as we are changing a lot. 

The core of HAWK is the same as in the paper except for the NLP parts which now come from Stanford (https://github.com/AKSW/NLIWOD/) we just moved the github repositories closer together to have a faster development environment. 

Currently, HAWK runs against DBpedia 2016-04 with our internal SPARQL endpoint based on Jena FUSEKI so we can run using the "text:query" predicate.  Pruning and ranking are the same but we look forward to replace them with a new query ranking technique. 

If you have any further questions please ask them
