### ISSUE TITLE
[QA.commons] Create a QALD JSON writer

### ISSUE THREAD

**Issue by RicardoUsbeck** [AKSW/NLIWOD#3]
Create a QALD JSON writer as a util class

**Comment by RicardoUsbeck** [comment]
It should have a function to also allow transforming of www.w3.org/TR/sparql11-results-json/ to QALD JSON

**Comment by JonathanHuthmann** [comment]
Since https://github.com/AKSW/NLIWOD/commit/0e06340e0c678f4d6de80196c26e8feb00f3c2c5

**Comment by JonathanHuthmann** [comment]
Since: https://github.com/AKSW/NLIWOD/commit/0e06340e0c678f4d6de80196c26e8feb00f3c2c5
you can read/write ExtendedJson and QaldJson formats. Both use class EJAnswers to store  result sets. the structure of EJAnswers is eqivalent to the one proposed here:https://www.w3.org/TR/sparql11-results-json/ 
So, if you want to load a result set like this, you can do so with: 
```
EJAnswers answers = (EJAnswers) ExtendedQALDJSONLoader.readJson(new File("path""), EJAnswers.class);
```
And add this to a QaldJson like this 
```
QaldJson qJson= new QaldJson();
QaldQuestionEntry entry=new QaldQuestionEntry();
entry.getAnswers().add(answers);
		
qJson.getQuestions().add(entry);
```
For ExtendedJson its very similar.
